In [2]:
import pandas as pd
import numpy as np
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

DATA_RAW = PROJECT_ROOT / "data" / "raw"
DATA_PROCESSED = PROJECT_ROOT / "data" / "processed"
OUTPUT_TABLES = PROJECT_ROOT / "outputs" / "tables"
OUTPUT_FIGURES = PROJECT_ROOT / "outputs" / "figures"

PROJECT_ROOT

PosixPath('/Users/tstanton/Desktop/soccer-event-data/soccer-xT-project')

In [14]:
import sys

sys.path.append(str(PROJECT_ROOT))

from src.loaders.statsbomb_loader import convert_statsbomb_to_standard

In [15]:
standard_events = convert_statsbomb_to_standard(events)

standard_events.head()

,match_id,period,timestamp_seconds,team,player,event_type,start_x,start_y,end_x,end_y,outcome,possession_id,source_event_id,source
0,7585,1,0.00,Colombia,NaN,starting xi,NaN,NaN,NaN,NaN,successful,1,de3be98d-e227-475b-bd55-f57a6a89d308,statsbomb
1,7585,1,0.00,England,NaN,starting xi,NaN,NaN,NaN,NaN,successful,1,f50ccda4-b768-4f07-9136-8f79fd17dac5,statsbomb
2,7585,1,0.00,England,NaN,half start,NaN,NaN,NaN,NaN,successful,1,b5e98805-0a22-4a5e-a306-7d40651a0f6e,statsbomb
3,7585,1,0.00,Colombia,NaN,half start,NaN,NaN,NaN,NaN,successful,1,762b829f-5f24-4dd7-bfe2-da7e289838bb,statsbomb
4,7585,1,0.24,Colombia,Radamel Falcao García Zárate,pass,60.0,40.0,50.0,41.0,successful,2,d4883f20-ce68-4f84-b26a-a049a13cb6be,statsbomb

In [3]:
STANDARD_COLUMNS = [
    "match_id",
    "period",
    "timestamp_seconds",
    "team",
    "player",
    "event_type",
    "start_x",
    "start_y",
    "end_x",
    "end_y",
    "outcome",
    "possession_id",
    "source_event_id",
    "source"
]

STANDARD_COLUMNS

['match_id',
 'period',
 'timestamp_seconds',
 'team',
 'player',
 'event_type',
 'start_x',
 'start_y',
 'end_x',
 'end_y',
 'outcome',
 'possession_id',
 'source_event_id',
 'source']

In [4]:
from mplsoccer import Sbopen

parser = Sbopen()

competitions = parser.competition()
competitions[['competition_id', 'season_id', 'competition_name', 'season_name']].head(30)

    competition_id  season_id         competition_name season_name
0                9        281            1. Bundesliga   2023/2024
1                9         27            1. Bundesliga   2015/2016
2             1267        107   African Cup of Nations        2023
3               16          4         Champions League   2018/2019
4               16          1         Champions League   2017/2018
5               16          2         Champions League   2016/2017
6               16         27         Champions League   2015/2016
7               16         26         Champions League   2014/2015
8               16         25         Champions League   2013/2014
9               16         24         Champions League   2012/2013
10              16         23         Champions League   2011/2012
11              16         22         Champions League   2010/2011
12              16         21         Champions League   2009/2010
13              16         41         Champions League   2008/2009
14              16         39         Champions League   2006/2007
15              16         37         Champions League   2004/2005
16              16         44         Champions League   2003/2004
17              16         76         Champions League   1999/2000
18              16        277         Champions League   1972/1973
19              16         71         Champions League   1971/1972
20              16        276         Champions League   1970/1971
21             223        282             Copa America        2024
22              87         84             Copa del Rey   1983/1984
23              87        268             Copa del Rey   1982/1983
24              87        279             Copa del Rey   1977/1978
25              37         90  FA Women's Super League   2020/2021
26              37         42  FA Women's Super League   2019/2020
27              37          4  FA Women's Super League   2018/2019
28            1470        274       FIFA U20 World Cup        1979
29              43        106           FIFA World Cup        2022

In [5]:
matches = parser.match(competition_id=43, season_id=3)

matches[['match_id', 'home_team_name', 'away_team_name', 'match_date']].head()

   match_id home_team_name away_team_name match_date
0      7585       Colombia        England 2018-07-03
1      7570        England        Belgium 2018-06-28
2      7586         Sweden    Switzerland 2018-07-03
3      7557           Iran       Portugal 2018-06-25
4      7542       Portugal        Morocco 2018-06-20

In [6]:
match_id = matches.iloc[0]['match_id']

events, related, freeze, tactics = parser.event(match_id)

events.head()

,id,index,period,timestamp,minute,second,possession,duration,match_id,type_id,...,foul_committed_card_id,foul_committed_card_name,foul_committed_penalty,foul_won_penalty,block_offensive,substitution_replacement_id,substitution_replacement_name,shot_first_time,pass_goal_assist,shot_deflected
0,de3be98d-e227-475b-bd55-f57a6a89d308,1,1,00:00:00,0,0,1,0.000,7585,35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,f50ccda4-b768-4f07-9136-8f79fd17dac5,2,1,00:00:00,0,0,1,0.754,7585,35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,b5e98805-0a22-4a5e-a306-7d40651a0f6e,3,1,00:00:00,0,0,1,9.320,7585,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,762b829f-5f24-4dd7-bfe2-da7e289838bb,4,1,00:00:00,0,0,1,9.053,7585,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,d4883f20-ce68-4f84-b26a-a049a13cb6be,5,1,00:00:00.240000,0,0,2,0.240,7585,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
events.columns.tolist()

['id',
 'index',
 'period',
 'timestamp',
 'minute',
 'second',
 'possession',
 'duration',
 'match_id',
 'type_id',
 'type_name',
 'possession_team_id',
 'possession_team_name',
 'play_pattern_id',
 'play_pattern_name',
 'team_id',
 'team_name',
 'tactics_formation',
 'player_id',
 'player_name',
 'position_id',
 'position_name',
 'pass_recipient_id',
 'pass_recipient_name',
 'pass_length',
 'pass_angle',
 'pass_height_id',
 'pass_height_name',
 'end_x',
 'end_y',
 'sub_type_id',
 'sub_type_name',
 'body_part_id',
 'body_part_name',
 'x',
 'y',
 'under_pressure',
 'outcome_id',
 'outcome_name',
 'counterpress',
 'pass_cross',
 'ball_recovery_recovery_failure',
 'pass_switch',
 'shot_statsbomb_xg',
 'end_z',
 'shot_follows_dribble',
 'technique_id',
 'technique_name',
 'goalkeeper_position_id',
 'goalkeeper_position_name',
 'pass_assisted_shot_id',
 'pass_shot_assist',
 'shot_key_pass_id',
 'aerial_won',
 'foul_won_defensive',
 'shot_open_goal',
 'foul_committed_advantage',
 'foul_won_advantage',
 'pass_backheel',
 'dribble_nutmeg',
 'pass_deflected',
 'block_deflection',
 'bad_behaviour_card_id',
 'bad_behaviour_card_name',
 'foul_committed_card_id',
 'foul_committed_card_name',
 'foul_committed_penalty',
 'foul_won_penalty',
 'block_offensive',
 'substitution_replacement_id',
 'substitution_replacement_name',
 'shot_first_time',
 'pass_goal_assist',
 'shot_deflected']

In [8]:
def timestamp_to_seconds(timestamp):
    """
    Converts StatsBomb timestamp format to seconds.
    Example: '00:12:34.567' -> 754.567
    """
    if pd.isna(timestamp):
        return np.nan

    h, m, s = str(timestamp).split(":")
    return int(h) * 3600 + int(m) * 60 + float(s)


def convert_statsbomb_to_standard(events):
    """
    Convert StatsBomb events into our universal event schema.
    """

    standard = pd.DataFrame()

    standard["match_id"] = events["match_id"]
    standard["period"] = events["period"]
    standard["timestamp_seconds"] = events["timestamp"].apply(timestamp_to_seconds)

    standard["team"] = events["team_name"]
    standard["player"] = events["player_name"]

    standard["event_type"] = events["type_name"].str.lower()

    standard["start_x"] = events["x"]
    standard["start_y"] = events["y"]
    standard["end_x"] = events["end_x"]
    standard["end_y"] = events["end_y"]

    standard["outcome"] = np.where(
        events["outcome_name"].isna(),
        "successful",
        events["outcome_name"].str.lower()
    )

    standard["possession_id"] = events["possession"]

    standard["source_event_id"] = events["id"]
    standard["source"] = "statsbomb"

    return standard[STANDARD_COLUMNS]

In [9]:
standard_events = convert_statsbomb_to_standard(events)

standard_events.head(20)

,match_id,period,timestamp_seconds,team,player,event_type,start_x,start_y,end_x,end_y,outcome,possession_id,source_event_id,source
0,7585,1,0.000,Colombia,NaN,starting xi,NaN,NaN,NaN,NaN,successful,1,de3be98d-e227-475b-bd55-f57a6a89d308,statsbomb
1,7585,1,0.000,England,NaN,starting xi,NaN,NaN,NaN,NaN,successful,1,f50ccda4-b768-4f07-9136-8f79fd17dac5,statsbomb
2,7585,1,0.000,England,NaN,half start,NaN,NaN,NaN,NaN,successful,1,b5e98805-0a22-4a5e-a306-7d40651a0f6e,statsbomb
3,7585,1,0.000,Colombia,NaN,half start,NaN,NaN,NaN,NaN,successful,1,762b829f-5f24-4dd7-bfe2-da7e289838bb,statsbomb
4,7585,1,0.240,Colombia,Radamel Falcao García Zárate,pass,60.0,40.0,50.0,41.0,successful,2,d4883f20-ce68-4f84-b26a-a049a13cb6be,statsbomb
5,7585,1,0.480,Colombia,Juan Fernando Quintero Paniagua,ball receipt,50.0,41.0,NaN,NaN,successful,2,5fc9acb8-88c3-4cfb-ad9c-fc250c0dffde,statsbomb
6,7585,1,0.480,Colombia,Juan Fernando Quintero Paniagua,carry,50.0,41.0,51.0,40.0,successful,2,b948f032-4c54-4782-a71a-ffeed8908d00,statsbomb
7,7585,1,1.000,England,Harry Kane,pressure,62.0,31.0,NaN,NaN,successful,2,a3300067-d4d2-43ef-bc96-239b4aebc98f,statsbomb
8,7585,1,2.120,Colombia,Juan Fernando Quintero Paniagua,pass,51.0,40.0,47.0,54.0,successful,2,9bdb71f9-c87b-4a66-96f0-def5312ca921,statsbomb
9,7585,1,3.440,Colombia,Carlos Alberto Sánchez Moreno,ball receipt,47.0,54.0,NaN,NaN,successful,2,05d8e5e5-37fe-4bad-8b21-2dbdff9b56d2,statsbomb
10,7585,1,3.440,Colombia,Carlos Alberto Sánchez Moreno,carry,47.0,54.0,49.0,55.0,successful,2,2ffa2904-8b47-4817-af26-aa9ac8d2881a,statsbomb
11,7585,1,4.200,Colombia,Carlos Alberto Sánchez Moreno,pass,49.0,55.0,65.0,79.0,successful,2,6cb0d85d-bd14-42e3-9c2d-7f99ce437796,statsbomb
12,7585,1,5.360,Colombia,Santiago Arias Naranjo,ball receipt,65.0,79.0,NaN,NaN,successful,2,0cf688d1-8134-4338-a5ea-e8d58dc5719e,statsbomb
13,7585,1,5.360,Colombia,Santiago Arias Naranjo,carry,65.0,79.0,66.0,78.0,successful,2,e70cdfb1-663c-431d-8a96-8a138a44b5e4,statsbomb
14,7585,1,5.412,England,Bamidele Alli,pressure,53.0,10.0,NaN,NaN,successful,2,8c4a54c0-1df5-4c4a-ad8e-8afe086b9648,statsbomb
15,7585,1,6.720,Colombia,Santiago Arias Naranjo,pass,66.0,78.0,96.0,59.0,incomplete,2,f8494960-ec60-4fa4-a565-b3c89757e92b,statsbomb
16,7585,1,8.520,England,Harry Maguire,pass,25.0,22.0,32.0,2.0,successful,2,d926ec5d-b9f7-43f8-97cd-43632bcd3cb9,statsbomb
17,7585,1,10.440,Colombia,Santiago Arias Naranjo,pressure,84.0,77.0,NaN,NaN,successful,2,02765261-9d69-4030-bbad-64752e3a65c3,statsbomb
18,7585,1,11.080,England,Bamidele Alli,ball receipt,32.0,2.0,NaN,NaN,successful,2,34dd393c-200e-4244-8f40-5ec7f0c369c8,statsbomb
19,7585,1,11.080,England,Bamidele Alli,pass,32.0,2.0,25.0,17.0,incomplete,2,9b85733f-f9cc-4dbf-9890-afa866efddb4,statsbomb

In [10]:
standard_events["event_type"].value_counts()

event_type
pass               1161
ball receipt       1066
carry               851
pressure            342
ball recovery       113
duel                 62
clearance            50
goal keeper          44
block                43
shot                 41
miscontrol           36
foul committed       36
foul won             35
dribble              29
camera on            20
dribbled past        16
dispossessed         14
interception         12
half start           10
half end             10
substitution          8
injury stoppage       6
50/50                 4
bad behaviour         3
starting xi           2
camera off            2
player off            1
player on             1
tactical shift        1
Name: count, dtype: int64

In [11]:
output_path = DATA_PROCESSED / f"standard_events_match_{match_id}.csv"

standard_events.to_csv(output_path, index=False)

output_path

PosixPath('/Users/tstanton/Desktop/soccer-event-data/soccer-xT-project/data/processed/standard_events_match_7585.csv')

In [12]:
pd.read_csv(output_path).head()

,match_id,period,timestamp_seconds,team,player,event_type,start_x,start_y,end_x,end_y,outcome,possession_id,source_event_id,source
0,7585,1,0.00,Colombia,NaN,starting xi,NaN,NaN,NaN,NaN,successful,1,de3be98d-e227-475b-bd55-f57a6a89d308,statsbomb
1,7585,1,0.00,England,NaN,starting xi,NaN,NaN,NaN,NaN,successful,1,f50ccda4-b768-4f07-9136-8f79fd17dac5,statsbomb
2,7585,1,0.00,England,NaN,half start,NaN,NaN,NaN,NaN,successful,1,b5e98805-0a22-4a5e-a306-7d40651a0f6e,statsbomb
3,7585,1,0.00,Colombia,NaN,half start,NaN,NaN,NaN,NaN,successful,1,762b829f-5f24-4dd7-bfe2-da7e289838bb,statsbomb
4,7585,1,0.24,Colombia,Radamel Falcao García Zárate,pass,60.0,40.0,50.0,41.0,successful,2,d4883f20-ce68-4f84-b26a-a049a13cb6be,statsbomb